export const PHONE = {
  href: "tel:+4917620222200",
  display: "0176 2022 2200",
};

export const SERVICES = [
  {
    slug: "rohrreinigung",
    label: "Rohrreinigung",
    heroLine2: "Verstopfungen schnell beseitigen",
    tagline: "Professionelle Rohrreinigung – schnell und zuverlässig",
    image: "rohrreinigung-fachmann-einsatz.webp",
    imageSm: "rohrreinigung-fachmann-einsatz-sm.webp",
  },
  {
    slug: "kamera-inspektion",
    label: "TV-Kamera-Inspektion",
    heroLine2: "Präzise Diagnose per Kamera",
    tagline: "Kamerabefahrung und Rohrortung mit Dokumentation",
    image: "kamerainspektion-kanal-garten.webp",
    imageSm: "kamerainspektion-kanal-garten-sm.webp",
  },
  {
    slug: "rohrreparatur",
    label: "Rohrreparatur",
    heroLine2: "Reparatur & Sanierung",
    tagline: "Fachgerechte Rohrreparaturen für alle Materialien",
    image: "rohrsanierung-inliner-verfahren.webp",
    imageSm: "rohrsanierung-inliner-verfahren-sm.webp",
  },
  {
    slug: "leckageortung",
    label: "Leckageortung",
    heroLine2: "Lecks und Rohrbrüche finden",
    tagline: "Schadstellensuche und Leckageortung vor Ort",
    image: "rohrreinigung-fachmann-einsatz.webp",
    imageSm: "rohrreinigung-fachmann-einsatz-sm.webp",
  },
  {
    slug: "abwasserreinigung",
    label: "Abwasserreinigung",
    heroLine2: "Grundreinigung von Leitungen",
    tagline: "Entfernung von Urinstein, Kalk und Fettablagerungen",
    image: "kanalreinigung-hochdruck-rohr.webp",
    imageSm: "kanalreinigung-hochdruck-rohr-sm.webp",
  },
  {
    slug: "hebeanlage-wartung",
    label: "Hebeanlagen-Service",
    heroLine2: "Wartung & Störungsbeseitigung",
    tagline: "Service für Hebeanlagen und Rückstausysteme",
    image: "kanalsanierung-liner-einbau.webp",
    imageSm: "kanalsanierung-liner-einbau-sm.webp",
  },
  {
    slug: "sanitaerarbeiten",
    label: "Sanitärarbeiten",
    heroLine2: "Montage & Reparatur",
    tagline: "WC, Armaturen, Siphon und Wasserleitungen",
    image: "toilette-verstopft-notfall-bad.webp",
    imageSm: "toilette-verstopft-notfall-bad-sm.webp",
  },
  {
    slug: "wasserschaden",
    label: "Wasserschaden",
    heroLine2: "Nasssaugarbeiten & Pumpen",
    tagline: "Wasserentfernung bei Keller- und Überschwemmungsschäden",
    image: "abflussreinigung-kueche-profi.webp",
    imageSm: "abflussreinigung-kueche-profi-sm.webp",
  },
  {
    slug: "notdienst",
    label: "24h Notdienst",
    heroLine2: "Soforthilfe rund um die Uhr",
    tagline: "Notdienst bei Verstopfung, Rohrbruch und Sanitär-Notfällen",
    image: "notdienst-rohrreinigung-sofort.webp",
    imageSm: "notdienst-rohrreinigung-sofort-sm.webp",
  },
];
